export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_LOADING = "SET_LOADING";
export const SET_QUIZ_INFO = "SET_QUIZ_INFO";
export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_SCORE = "UPDATE_USER_SCORE";
export const SET_QUESTION_COMPLETED = "SET_QUESTION_COMPLETED";
export const SET_COMPLETED_TO_DEFAULT = "SET_COMPLETED_TO_DEFAULT";
export const SET_USER_INFO_TO_DEFAULT = "SET_USER_INFO_TO_DEFAULT";
